version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_DATABASE: twitch
      MONGO_INITDB_ROOT_PASSWORD: dev
    ports:
      - "27017:27017"

  worker:
    build: .
    restart: always
    command: yarn dev
    environment:
      TOKEN: ${TOKEN}
      USERNAME: ${USERNAME}
      MONGOURI: ${MONGOURI}
    volumes:
      - .:/home/node/app/
      - /home/node/app/node_modules
    depends_on:
      - mongo
    links:
      - mongo